# Generated by Django 3.2.4 on 2021-10-10 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 10, 15, 53, 32, 610680))),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 10, 15, 53, 32, 610680))),
            ],
        ),
    ]
