# Generated by Django 3.2.4 on 2021-11-20 07:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedular',
            name='recurrenceExceptions',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='schedular',
            name='recurrenceId',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedular',
            name='recurrenceRule',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='schedular',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 20, 11, 34, 50, 734265)),
        ),
        migrations.AlterField(
            model_name='schedular',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 20, 11, 34, 50, 734265)),
        ),
        migrations.AlterField(
            model_name='schedular',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
