# Generated by Django 3.2.4 on 2021-09-20 07:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reactshedularDj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='detail',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='react',
            name='name',
        ),
        migrations.AddField(
            model_name='react',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 20, 11, 50, 4, 188355)),
        ),
        migrations.AddField(
            model_name='react',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 20, 11, 50, 4, 188355)),
        ),
        migrations.AddField(
            model_name='react',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='react',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
