# Generated by Django 3.2.4 on 2021-09-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactshedularDj', '0002_auto_20210920_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='task_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='react',
            name='end',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='react',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='react',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
