# Generated by Django 3.2.4 on 2021-09-21 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactshedularDj', '0003_auto_20210921_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='task_id',
            new_name='TaskId',
        ),
        migrations.AlterField(
            model_name='react',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 21, 13, 41, 35, 609577)),
        ),
        migrations.AlterField(
            model_name='react',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 21, 13, 41, 35, 609577)),
        ),
    ]
