# Generated by Django 3.2.4 on 2021-09-26 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactshedularDj', '0004_auto_20210921_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 26, 21, 33, 39, 526925)),
        ),
        migrations.AlterField(
            model_name='react',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 26, 21, 33, 39, 526925)),
        ),
    ]
